export enum DateFormats {
  MMMM_DD_YYYY = "MMMM DD, YYYY",
  DD_MM_YYYY_WITH_DOT = "DD.MM.YYYY",
  DD_MM_YYYY_WITH_SLASH = "DD/MM/YYYY",
  YYYY_MM_DD_WITH_HYPEN = "YYYY-MM-DD",
  DD_MM_YYYY_WITH_HYPHEN = "DD-MM-YYYY",
  DD_MM_YYYY_HH_mm = "DD/MM/YYYY HH:mm",
  DD_MMM_YYYY_WITH_SPACE = "DD MMM YYYY",
}
